# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv", sep=',')

In [3]:
baby_names.head(10)

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

### Step 4. See the first 10 entries

In [4]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [6]:
baby_names = baby_names.drop(columns=['Unnamed: 0',"Id"])

### Step 6. What year has the highest number of baby names in the dataset?

In [29]:
baby_names["Year"].value_counts().idxmax()

np.int64(2008)

### Step 7. Is there more male or female names in the dataset?

In [32]:
baby_names["Gender"].value_counts().idxmax()

'F'

### Step 8. Group the dataset by name and assign to names

In [34]:
names = baby_names.groupby("Name")

### Step 9. How many different names exist in the dataset?

In [49]:
len(names)

17632

### Step 10. What is the name with most occurrences?

In [73]:
names.Name.idxmax()

Name
Aaban      693699
Aadan      120728
Aadarsh    323950
Aaden       17728
Aadhav     138429
            ...
Zyra        98915
Zyrah       95392
Zyren      910625
Zyria      235711
Zyriah     235986
Name: Name, Length: 17632, dtype: int64

In [63]:
baby_names[baby_names["Count"] == baby_names["Count"].max()]

          Name  Year Gender State  Count
107416  Daniel  2004      M    CA   4167

### Step 11. How many different names have the least occurrences?

In [72]:

baby_names.Name.nunique()

17632

### Step 12. What is the median name occurrence?

In [75]:
names[names.Count == names.Count.median()]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (17632, 2) + inhomogeneous part.

### Step 13. What is the standard deviation of names?

In [76]:
names['Count'].sum().std()

11006.069467891111

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [77]:
names.describe()

          Year                                                           \
         count         mean       std     min      25%     50%      75%
Name
Aaban      2.0  2013.500000  0.707107  2013.0  2013.25  2013.5  2013.75
Aadan      4.0  2009.750000  2.872281  2008.0  2008.00  2008.5  2010.25
Aadarsh    1.0  2009.000000       NaN  2009.0  2009.00  2009.0  2009.00
Aaden    196.0  2010.015306  2.044322  2005.0  2008.00  2010.0  2011.00
Aadhav     1.0  2014.000000       NaN  2014.0  2014.00  2014.0  2014.00
...        ...          ...       ...     ...      ...     ...      ...
Zyra       7.0  2012.142857  2.115701  2008.0  2011.50  2013.0  2013.50
Zyrah      2.0  2012.000000  1.414214  2011.0  2011.50  2012.0  2012.50
Zyren      1.0  2013.000000       NaN  2013.0  2013.00  2013.0  2013.00
Zyria     10.0  2008.900000  2.685351  2005.0  2007.25  2008.0  2010.50
Zyriah     9.0  2009.666667  2.915476  2006.0  2007.00  2009.0  2012.00

                 Count
            max  count       mean        std  min   25%   50%    75%    max
Name
Aaban    2014.0    2.0   6.000000   0.000000  6.0  6.00   6.0   6.00    6.0
Aadan    2014.0    4.0   5.750000   0.957427  5.0  5.00   5.5   6.25    7.0
Aadarsh  2009.0    1.0   5.000000        NaN  5.0  5.00   5.0   5.00    5.0
Aaden    2014.0  196.0  17.479592  21.154974  5.0  6.00  10.0  20.00  158.0
Aadhav   2014.0    1.0   6.000000        NaN  6.0  6.00   6.0   6.00    6.0
...         ...    ...        ...        ...  ...   ...   ...    ...    ...
Zyra     2014.0    7.0   6.000000   1.154701  5.0  5.00   6.0   6.50    8.0
Zyrah    2013.0    2.0   5.500000   0.707107  5.0  5.25   5.5   5.75    6.0
Zyren    2013.0    1.0   6.000000        NaN  6.0  6.00   6.0   6.00    6.0
Zyria    2014.0   10.0   5.900000   0.737865  5.0  5.25   6.0   6.00    7.0
Zyriah   2014.0    9.0   6.444444   1.666667  5.0  5.00   6.0   7.00   10.0

[17632 rows x 16 columns]