# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [2]:
cars1  = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv", sep=',')
cars2  = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv", sep=',')

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [4]:
cars1  = cars1.rename(columns={"Unnamed: 9": 'onoma1', "Unnamed: 10": 'onoma2', "Unnamed: 11":"onoma3", "Unnamed: 12":"onoma4", "Unnamed: 13":"onoma5"})

In [5]:
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,onoma1,onoma2,onoma3,onoma4,onoma5
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

### Step 5. What is the number of observations in each dataset?

In [7]:
cars1.info()
cars2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           198 non-null    float64
 1   cylinders     198 non-null    int64
 2   displacement  198 non-null    int64
 3   horsepower    198 non-null    object
 4   weight        198 non-null    int64
 5   acceleration  198 non-null    float64
 6   model         198 non-null    int64
 7   origin        198 non-null    int64
 8   car           198 non-null    object
 9   onoma1        0 non-null      float64
 10  onoma2        0 non-null      float64
 11  onoma3        0 non-null      float64
 12  onoma4        0 non-null      float64
 13  onoma5        0 non-null      float64
dtypes: float64(7), int64(5), object(2)
memory usage: 21.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           200 non-null    float64
 1   cylinders     200 non-null    int64
 2   displacement  200 non-null    int64
 3   horsepower    200 non-null    object
 4   weight        200 non-null    int64
 5   acceleration  200 non-null    float64
 6   model         200 non-null    int64
 7   origin        200 non-null    int64
 8   car           200 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 14.2+ KB

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [12]:
cars = pd.concat([cars1,cars2])

In [14]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 398 entries, 0 to 199
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    int64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model         398 non-null    int64
 7   origin        398 non-null    int64
 8   car           398 non-null    object
 9   onoma1        0 non-null      float64
 10  onoma2        0 non-null      float64
 11  onoma3        0 non-null      float64
 12  onoma4        0 non-null      float64
 13  onoma5        0 non-null      float64
dtypes: float64(7), int64(5), object(2)
memory usage: 46.6+ KB

In [10]:

cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,onoma1,onoma2,onoma3,onoma4,onoma5
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [11]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [16]:
cars["owners"] = np.random.randint(15000, 73000, size=len(cars))

### Step 8. Add the column owners to cars

In [17]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,onoma1,onoma2,onoma3,onoma4,onoma5,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,27112
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,52238
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,28288
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,39494
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,35057